{{- include "chatfit.validateValues" . -}}
{{- if eq (default "pvc" .Values.persistence.type) "pvc" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "chatfit.fullname" . }}-data
  labels:
    {{- include "chatfit.labels" . | nindent 4 }}
  {{- if .Values.persistence.keep }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- with .Values.persistence.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
{{- end }}
