{{- include "chatfit.validateValues" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chatfit.apiServiceName" . }}
  labels:
    {{- include "chatfit.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: http
  selector:
    {{- include "chatfit.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
